CREATE DATABASE GCTripPlannerDB;
GO

USE GCTripPlannerDB;

CREATE TABLE [User] (
UserID INT PRIMARY KEY IDENTITY(1,1),
UserName NVARCHAR(30) NOT NULL,
[Address] NVARCHAR(60),
DOB DATE
)

CREATE TABLE Passport(
PassportNumber INT PRIMARY KEY,
Expiration DATE NOT NULL,
PassportAddress NVARCHAR (60)
)

CREATE TABLE Trip(
TripID INT PRIMARY KEY IDENTITY(1,1),
Budget INT,
StartLoc NVARCHAR(30),
EndLoc NVARCHAR(30),
TravelType NVARCHAR(16),
StartDate DATE,
EndDate DATE
)
GO

CREATE TABLE Hotel (
HotelID NCHAR(5) PRIMARY KEY,
CheckInDate DATE,
CheckOutDate DATE,
PerNight DECIMAL(9,2),
HotelAddress NVARCHAR(60),
HotelPhone NCHAR(10)
)

GO

ALTER TABLE Trip 
	ADD Planner INT 
	FOREIGN KEY REFERENCES [User](UserID);
ALTER TABLE Passport 
	ADD [Owner] INT 
	FOREIGN KEY REFERENCES [User](UserID) UNIQUE;

CREATE TABLE HotelTrip (
HotelTripID INT PRIMARY KEY IDENTITY(1,1),
HotelID NCHAR(5) FOREIGN KEY REFERENCES Hotel(HotelID),
TripID INT FOREIGN KEY REFERENCES Trip(TripID)
)

GO